export const rolesData = [
  { value: "CFO", label: "CFO" },
  { value: "CEO", label: "CEO" },
  { value: "FP&A Manager", label: "FP&A Manager" },
  { value: "Financial Lead", label: "Financial Lead" },
  { value: "FP&A Lead", label: "FP&A Lead" },
  { value: "Senior Financial Analyst", label: "Senior Financial Analyst" },
  { value: "Financial Analyst", label: "Financial Analyst" },
  { value: "Senior Business Analyst", label: "Senior Business Analyst" },
  { value: "Business Analyst", label: "Business Analyst" },
  { value: "Investor Relations Manager", label: "Investor Relations Manager" },
  { value: "Senior Strategist", label: "Senior Strategist" },
  { value: "Strategist", label: "Strategist" },
  { value: "Investor Relations Officer", label: "Investor Relations Officer" },
  {
    value: "Senior Investor Relations Officer",
    label: "Senior Investor Relations Officer",
  },
  { value: "Senior Budgeting Analyst", label: "Senior Budgeting Analyst" },
  { value: "Budgeting Analyst", label: "Budgeting Analyst" },
  { value: "Financial Consultant", label: "Financial Consultant" },
  { value: "Business Consultant", label: "Business Consultant" },
  { value: "other", label: "Other" },
];
