FROM node:20 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV chokidar_usePolling=true
ARG API_URL
ENV REACT_APP_API_URL=$API_URL
ARG GOOGLE_CLIENT_ID
ENV REACT_APP_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ARG MICROSOFT_CLIENT_ID
ENV REACT_APP_MICROSOFT_CLIENT_ID=$MICROSOFT_CLIENT_ID
ARG QUICKBOOKS_CLIENT_ID
ENV REACT_APP_QUICKBOOKS_CLIENT_ID=$QUICKBOOKS_CLIENT_ID
ARG QUICKBOOKS_REDIRECT_URI
ENV REACT_APP_QUICKBOOKS_REDIRECT_URI=$QUICKBOOKS_REDIRECT_URI
ARG TAG_MANAGER_ID
ENV REACT_APP_TAG_MANAGER_ID=$TAG_MANAGER_ID
ARG REACT_APP_NEW_RELIC_APPLICATION_ID
ENV REACT_APP_NEW_RELIC_APPLICATION_ID=$REACT_APP_NEW_RELIC_APPLICATION_ID
ARG REACT_APP_NEW_RELIC_LICENSE_KEY
ENV REACT_APP_NEW_RELIC_LICENSE_KEY=$REACT_APP_NEW_RELIC_LICENSE_KEY
ARG REACT_APP_NEW_RELIC_AGENT_ID
ENV REACT_APP_NEW_RELIC_AGENT_ID=$REACT_APP_NEW_RELIC_AGENT_ID
ARG SUBSBASE_REDIRECT_URI
ENV REACT_APP_SUBSBASE_REDIRECT_URI=$SUBSBASE_REDIRECT_URI
ARG REACT_APP_AWS_REGION
ENV REACT_APP_AWS_REGION=$REACT_APP_AWS_REGION
ARG REACT_APP_AWS_USER_POOL_ID
ENV REACT_APP_AWS_USER_POOL_ID=$REACT_APP_AWS_USER_POOL_ID
ARG REACT_APP_AWS_USER_POOLS_CLIENT_ID
ENV REACT_APP_AWS_USER_POOLS_CLIENT_ID=$REACT_APP_AWS_USER_POOLS_CLIENT_ID
ARG REACT_APP_AWS_DOMAIN
ENV REACT_APP_AWS_DOMAIN=$REACT_APP_AWS_DOMAIN
ARG REACT_APP_AWS_REDIRECT
ENV REACT_APP_AWS_REDIRECT=$REACT_APP_AWS_REDIRECT
ARG REACT_APP_SUBSBASE_CUSTOM_PORTAL_URL
ENV REACT_APP_SUBSBASE_CUSTOM_PORTAL_URL=$REACT_APP_SUBSBASE_CUSTOM_PORTAL_URL
ARG REACT_APP_SUBSBASE_SITE_ID
ENV REACT_APP_SUBSBASE_SITE_ID=$REACT_APP_SUBSBASE_SITE_ID
RUN CI=false npm run build

FROM nginx:1.15 as dev
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx/nginxLA.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/nginx/.htpasswd /etc/nginx/.htpasswd
EXPOSE 80
HEALTHCHECK CMD curl --fail http://localhost:80/health || exit 1

FROM nginx:1.15 as prod
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80